---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  # Note: Dependency resolution will still include repository packages.
  - name: Upgrade the system using yay.
    kewlfft.aur.aur:
      upgrade: yes
      use: yay
      aur_only: no
    become: yes
    become_user: aur_builder

  - name: Install packages using yay
    kewlfft.aur.aur:
      use: yay
      name:
        - dmenu2
        - docker-credential-pass-bin
        - etcher-bin
        - flux-bin
        - google-chrome
        - google-cloud-sdk
        - gotask-taskfile
        - i3blocks-contrib
        - kind-bin
        - kubeseal-bin
        - lens-bin
        - mqtt-explorer-appimage
        - nerd-fonts-inconsolata
        - nerd-fonts-inconsolata-go
        - nodejs-markdownlint-cli
        - nvm
        - otf-inconsolata-dz-powerline
        - postman-bin
        - pyenv-virtualenv
        - spaceship-prompt
        - spotify
        - terraform-docs-bin
        - tflint-bin
        - tfsec
        - visual-studio-code-bin
        - yay
      state: latest
    become: yes
    become_user: aur_builder


  - name: install packages
    ansible.builtin.package:
      name:
        - community/zsh-syntax-highlighting
        - community/zsh-autosuggestions
        - community/yq
        - community/yarn
        - community/yamllint
        - community/x11-ssh-askpass
        - community/vault
        - community/ttf-liberation
        - community/ttf-font-awesome
        - community/ttf-fira-code
        - community/ttf-dejavu
        - community/tmux
        - community/tig
        - community/terraform
        - community/sops
        - community/semver
        - community/scrot
        - community/redis
        - community/ranger
        - community/pyenv
        - community/prettier
        - community/pacman-contrib
        - community/openbsd-netcat
        - community/nodejs
        - community/neovim
        - community/kustomize
        - community/kubectl
        - community/k9s
        - community/jq
        - community/iotop
        - community/iftop
        - community/i3status
        - community/i3lock
        - community/i3blocks
        - community/i3-gaps
        - community/helm
        - community/go
        - community/dunst
        - community/docker-compose
        - community/docker
        - community/discord
        - community/direnv
        - community/colordiff
        - community/barrier
        - community/ansible
        - community/alacritty
        - community/acpi

      state: latest
    become: yes

  # - name: copy wallpaper file
  #   copy:
  #     src: files/wallpaper.png
  #     dest: /usr/share/backgrounds/ansible-wallpaper.png
  #     owner: root
  #     group: root

  # - name: set wallpaper
  #   become_user: jay
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-uri"
  #     value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  # - name: set wallpaper position
  #   become_user: jay
  #   dconf:
  #     key: "/org/gnome/desktop/background/picture-options"
  #     value: "'zoom'"

  # - name: copy .bashrc file
  #   copy:
  #    src: files/bashrc
  #    dest: /home/jay/.bashrc
  #    owner: jay
  #    group: jay

  # - name: add ansible user
  #   user:
  #     name: velociraptor
  #     system: yes

  # - name: set up sudo for ansible user
  #   copy:
  #     src: files/sudoer_velociraptor
  #     dest: /etc/sudoers.d/velociraptor
  #     owner: root
  #     group: root
  #     mode: 0440

  # - name: add ansible-pull cron job
  #   cron:
  #     name: ansible auto-provision
  #     user: velociraptor
  #     minute: "*/10"
  #     job: ansible-pull -o -U https://github.com/jlacroix82/ansible_pull_tutorial.git
